# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('engine', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=150)),
                ('previous_owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('purchase', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('dealer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customers', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
    ]
