# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='car',
            name='weight',
        ),
        migrations.AddField(
            model_name='car',
            name='source',
            field=models.FileField(default='abc', upload_to='cars/%Y/%m/%d/'),
        ),
    ]
