# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171204_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='d',
        ),
    ]
