# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171204_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='id',
            field=models.CharField(default='0', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17),
        ),
    ]
